"""ros2_control stack for the servo demo with the controllers generated by UniRoboLab.

    ros2 launch <this file> pkg:=servo_demo_rl_ros2control_policy

Starts robot_state_publisher, ros2_control_node (topic_based hardware -> the simulator's
/ServoDemo/joint_command) and the spawners for joint_state_broadcaster and the policy's
controller. The robot must already be spawned in the simulator (servo_demo_bringup.sh).
Derived from servo_demo_description/launch/servo_demo_spawn.launch.py without the
trajectory controller and the demo commander.
"""

import os

import xacro
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, GroupAction, OpaqueFunction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node, PushRosNamespace


def _setup(context):
    pkg = LaunchConfiguration("pkg").perform(context)
    controller = LaunchConfiguration("controller").perform(context)
    robot_name = "ServoDemo"
    desc = get_package_share_directory("servo_demo_description")
    doc = xacro.process_file(os.path.join(desc, "robots", "servo_demo.urdf.xacro"),
                             mappings={"use_sim": "true", "robot_name": robot_name})
    params = {"robot_description": doc.toprettyxml(indent="  ")}
    controllers_yaml = os.path.join(get_package_share_directory(pkg), "config", "controllers.yaml")
    cm = f"/{robot_name}/controller_manager"
    return [GroupAction([
        PushRosNamespace(robot_name),
        Node(package="robot_state_publisher", executable="robot_state_publisher", parameters=[params]),
        Node(package="controller_manager", executable="ros2_control_node",
             parameters=[params, controllers_yaml], output="screen"),
        Node(package="controller_manager", executable="spawner",
             arguments=["joint_state_broadcaster", "--controller-manager", cm], respawn=True, respawn_delay=5.0),
        Node(package="controller_manager", executable="spawner",
             arguments=[controller, "--controller-manager", cm], respawn=True, respawn_delay=5.0),
    ])]


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("pkg", description="generated policy package holding config/controllers.yaml"),
        DeclareLaunchArgument("controller", default_value="joint_group_position_controller"),
        OpaqueFunction(function=_setup),
    ])
